PROJECT_ID: 
LOCATION : 
BUCKET_URI : 
DEPLOYED_INDEX_EXCEL_ID : 
DEPLOYED_INDEX_WORD_AND_PDF_ID : 
INDEX_ID : 
ENDPOINT_ID : 

DIMENSIONS : 768
DISPLAY_NAME : 
EMBEDDING_DIR : 
PROJECT_NUMBER : 




# Change this if you need the VPC to be created.
CREATE_VPC : False